# 以下为站点信息
site_name: ECNU-WIKI
site_url: https://BetterECNU.github.io/ecnu-wiki

# 以下为仓库信息
repo_url: https://github.com/BetterECNU/ecnu-wiki
repo_name: BetterECNU/ecnu-wiki

theme:
  language: zh
  name: material # 设定主题为 material
  custom_dir: overrides # 启用giscus评论需要此行
  palette: #日夜模式切换
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple #基调色
      accent: green #强调色
      toggle:
        icon: material/weather-sunny
        name: 日间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple #基调色
      accent: green #强调色
      toggle:
        icon: material/weather-night
        name: 夜间模式
  icon:
    repo: fontawesome/brands/github # 设置git仓库图标
  
  features:
    - content.code.copy # 启用代码块复制按钮，尽管我觉得用不上
    - navigation.footer # 启用页尾上一页下一页按钮
    - navigation.instant # 内部链接即时加载
    - navigation.tabs # 页顶导航栏
    - navigation.tabs.sticky # 粘性导航栏
    - navigation.top # 回到顶部
    - toc.follow # 边栏自动滚动

plugins:
  - git-revision-date-localized:
      enable_creation_date: true # 页脚添加创建时间与最后更新时间
  - git-committers:
      repository: BetterECNU/ecnu-wiki
      branch: main # 页脚添加作者信息
  - search # 启用搜索功能

markdown_extensions: # markdown扩展插件
  - admonition # 启用注释语法扩展
  - footnotes # 添加页脚引用
  - pymdownx.arithmatex: # 数学公式支持
      generic: true
  - pymdownx.caret # 下划线与上标
  - pymdownx.details # 启用注释语法扩展
  - pymdownx.mark # 强调
  - pymdownx.superfences: # 启用注释语法扩展
      custom_fences: # 添加 mermaid 流程图支持
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde # 删除线与下标

extra_javascript: #js文件
  - javascripts/mathjax.js # 数学公式支持
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # 数学公式支持

nav:
  - "index.md"
